// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, version, source, payload, created_at, status, retry_count, last_attempt_at
FROM alerts WHERE id=?
`

func (q *Queries) GetAlertByID(ctx context.Context, id string) (Alert, error) {
	row := q.db.QueryRowContext(ctx, getAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Source,
		&i.Payload,
		&i.CreatedAt,
		&i.Status,
		&i.RetryCount,
		&i.LastAttemptAt,
	)
	return i, err
}

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (id, version, source, payload, created_at, status, retry_count)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAlertParams struct {
	ID         string    `json:"id"`
	Version    int64     `json:"version"`
	Source     string    `json:"source"`
	Payload    []byte    `json:"payload"`
	CreatedAt  time.Time `json:"created_at"`
	Status     string    `json:"status"`
	RetryCount int64     `json:"retry_count"`
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.ExecContext(ctx, insertAlert,
		arg.ID,
		arg.Version,
		arg.Source,
		arg.Payload,
		arg.CreatedAt,
		arg.Status,
		arg.RetryCount,
	)
	return err
}

const listAlertsBySource = `-- name: ListAlertsBySource :many
SELECT id, version, source, payload, created_at, status, retry_count, last_attempt_at
FROM alerts WHERE source=? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAlertsBySourceParams struct {
	Source string `json:"source"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListAlertsBySource(ctx context.Context, arg ListAlertsBySourceParams) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Source,
			&i.Payload,
			&i.CreatedAt,
			&i.Status,
			&i.RetryCount,
			&i.LastAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryState = `-- name: UpdateDeliveryState :exec
UPDATE alerts SET status=?, retry_count=?, last_attempt_at=? WHERE id=?
`

type UpdateDeliveryStateParams struct {
	Status        string       `json:"status"`
	RetryCount    int64        `json:"retry_count"`
	LastAttemptAt sql.NullTime `json:"last_attempt_at"`
	ID            string       `json:"id"`
}

func (q *Queries) UpdateDeliveryState(ctx context.Context, arg UpdateDeliveryStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryState,
		arg.Status,
		arg.RetryCount,
		arg.LastAttemptAt,
		arg.ID,
	)
	return err
}
