// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Message struct {
	ID            string       `json:"id"`
	Version       int32        `json:"version"`
	Input         string       `json:"input"`
	Payload       []byte       `json:"payload"`
	CreatedAt     time.Time    `json:"created_at"`
	Status        string       `json:"status"`
	RetryCount    int32        `json:"retry_count"`
	LastAttemptAt sql.NullTime `json:"last_attempt_at"`
}
