// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, version, input, payload, created_at, status, retry_count, last_attempt_at
FROM messages WHERE id=?
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Input,
		&i.Payload,
		&i.CreatedAt,
		&i.Status,
		&i.RetryCount,
		&i.LastAttemptAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, version, input, payload, created_at, status, retry_count)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ID         string    `json:"id"`
	Version    int32     `json:"version"`
	Input      string    `json:"input"`
	Payload    []byte    `json:"payload"`
	CreatedAt  time.Time `json:"created_at"`
	Status     string    `json:"status"`
	RetryCount int32     `json:"retry_count"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.Version,
		arg.Input,
		arg.Payload,
		arg.CreatedAt,
		arg.Status,
		arg.RetryCount,
	)
	return err
}

const listMessagesByInput = `-- name: ListMessagesByInput :many
SELECT id, version, input, payload, created_at, status, retry_count, last_attempt_at
FROM messages WHERE input=? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListMessagesByInputParams struct {
	Input  string `json:"input"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListMessagesByInput(ctx context.Context, arg ListMessagesByInputParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByInput, arg.Input, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Input,
			&i.Payload,
			&i.CreatedAt,
			&i.Status,
			&i.RetryCount,
			&i.LastAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryState = `-- name: UpdateDeliveryState :exec
UPDATE messages SET status=?, retry_count=?, last_attempt_at=? WHERE id=?
`

type UpdateDeliveryStateParams struct {
	Status        string       `json:"status"`
	RetryCount    int32        `json:"retry_count"`
	LastAttemptAt sql.NullTime `json:"last_attempt_at"`
	ID            string       `json:"id"`
}

func (q *Queries) UpdateDeliveryState(ctx context.Context, arg UpdateDeliveryStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryState,
		arg.Status,
		arg.RetryCount,
		arg.LastAttemptAt,
		arg.ID,
	)
	return err
}
